language: java

jdk: openjdk11

env:
  - IDEA_VERSION=2019.3.5

jobs:
  include:
    - stage: test
      script:
        - ./gradlew --console=plain check verifyPlugin
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console=plain buildPlugin